@DreamOn.HelloSudokuWebAPI_HostAddress = http://localhost:5198

GET {{DreamOn.HelloSudokuWebAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{DreamOn.HelloSudokuWebAPI_HostAddress}}/hellosudoku/
Accept: application/json

###
